### ISSUE TITLE
Add data-disable to the proposal submission form

### ISSUE THREAD

**Issue by nateberkopec** [NYCrb/cfp-app#4]
Once the proposal submission form button is pressed, we should use UJS `data-disable` to stop the button from being pressed again.

**Comment by yvoloshin** [comment]
I'm on it...

**Comment by stratigos** [comment]
Hi @yvoloshin, I actually just finished this one, making a PR now...

**Comment by yvoloshin** [comment]
Okay, thanks for letting me know @stratigos

**Comment by snuggs** [comment]
Should we close this @nateberkopec ?

**Comment by nateberkopec** [comment]
Oops yup forgot
